# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a814388e9f257d0b474a6bf8972dcea399f6beebd1006bb49158b0aed4f0de58031ea1f48c660d593346781d3fb1118642e687b5853aee164476562d63b6e228

test:
  secret_key_base: 7907e29ac494fbad50410211310922beef3007dcb714025f3bab427dd8c1e47da42734c1014955b379f48ae38eae6a099a53c440ff211e0ca858e24f444edd78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
